name: Build and test

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  GOPRIVATE: github.com/snabble

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Build and Test
        uses: ./.github/actions/build_and_test
